[package]
name = "tpm2"
description = "Core types and traits for communicating with a TPM 2.0"

# Inherit from Workspace Settings
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
# Implement conversions/traits which require std
std = []

# Only enable SHA2 by default
default = ["sha256", "sha384", "sha512"]
sha1 = []
sha256 = []
sha384 = []
sha512 = []
sm3_256 = []
sha3_256 = []
sha3_384 = []
sha3_512 = []

[dependencies]
bitflags = { workspace = true }
