use super::CryptoError;

/// Stateful random bit generator used for both the global TPM DRBG
/// and deterministic primary-key generation (`TPM2_CreatePrimary`).
pub trait Rng {
    /// Fills `dest` with generated bytes.
    fn fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), CryptoError>;

    /// Deterministically mixes `data` into the DRBG state.
    ///
    /// Used for `TPM2_StirRandom` on the global RNG, and for mixing `name`,
    /// `additional_data`, and hierarchy proof values into a seeded RNG in
    /// `TPM2_CreatePrimary`.
    fn reseed(&mut self, data: &[u8]) -> Result<(), CryptoError>;
}

impl Rng for ! {
    fn fill_bytes(&mut self, _: &mut [u8]) -> Result<(), CryptoError> {
        match *self {}
    }

    fn reseed(&mut self, _: &[u8]) -> Result<(), CryptoError> {
        match *self {}
    }
}

/// Cryptographic RNG factory interface for TPM implementations and clients.
#[allow(unused_variables)]
pub trait Random {
    type Rng: Rng;

    /// Instantiates a new RNG seeded from hardware/platform entropy
    /// (used to initialize the global TPM RNG).
    fn rng(&self) -> Result<Self::Rng, CryptoError> {
        Err(CryptoError::Unsupported)
    }

    /// Instantiates a deterministic RNG from `seed`
    /// (used for `TPM2_CreatePrimary`).
    fn rng_seeded(&self, seed: &[u8]) -> Result<Self::Rng, CryptoError> {
        Err(CryptoError::Unsupported)
    }
}
