[package]
name = "tpm2-crypto-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tpm2 = { workspace = true }
hex-literal = { workspace = true }
rsa = { version = "0.9.10", features = ["sha2", "sha1", "getrandom"] }
p256 = { version = "0.13.2", features = ["ecdsa", "arithmetic"] }
p384 = { version = "0.13", features = ["ecdsa", "arithmetic"] }
p521 = { version = "0.13", features = ["ecdsa", "arithmetic"] }
rand = "0.9.4"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
sha2 = "0.10.9"
sha1 = "0.10.6"
hmac = "0.12.1"


# Conditional backend dependencies
tpm2-crypto-rust = { path = "../rust", optional = true }
tpm2-crypto-crux = { path = "../crux", optional = true }
tpm2-crypto-bssl = { path = "../bssl", optional = true }

[features]
default = ["bssl"]
rust = ["dep:tpm2-crypto-rust"]
crux = ["dep:tpm2-crypto-crux"]
bssl = ["dep:tpm2-crypto-bssl"]

