use crate::handler::CommandHandler;
use crate::req_resp::RequestThenResponse;
use tpm2::Alg;
use tpm2::Marshal;
#[allow(unused_imports)]
use tpm2::TpmCc;
use tpm2::Unmarshal;
use tpm2::commands::responses;
use tpm2::commands::{Import, ImportHandles};
use tpm2::errors::{Position, TpmRc};

use crate::owned::OwnedPublicParmsAndId;
use crate::storage::NvStorage;
use crate::timer::TpmTimer;
use tpm2::crypto::kdf::kdfa;
use tpm2::crypto::{CryptoProvider, Rng};
use tpm2::{
    PublicParmsAndId, TpmaObject, TpmiAlgSymMode, TpmsSensitiveCreate, TpmtSensitive,
    TpmuSensitiveComposite,
};

impl<'a, 'b, C: CryptoProvider, S: NvStorage, T: TpmTimer, R: Rng + Sync>
    CommandHandler<'a, 'b, C, S, T, R>
{
    /// Handles the [TpmCc::Import] (`0x156`) command.
    ///
    /// # Description
    /// This command allows a duplicate key (created off-TPM or on another TPM using [TpmCc::Duplicate](duplicate.rs))
    /// to be imported under a parent key on the current TPM. It returns an encrypted private area (`out_private`)
    /// suitable for loading.
    ///
    /// # Spec Citation
    /// TCG TPM 2.0 Library Specification, Part 3: Commands, Section 13.3 (TPM2_Import).
    ///
    /// # Relationships
    /// - Takes the duplicate blob and seed generated by [TpmCc::Duplicate](duplicate.rs).
    /// - Re-encrypts the key under the parent key (`parent_handle`) so that it can be loaded using [TpmCc::Load](load.rs).
    pub fn import(&mut self, request_response: RequestThenResponse<'_, '_>) -> Result<(), TpmRc> {
        let mut request = request_response;

        let handles = request.try_unmarshal::<ImportHandles>()?;
        let parent_handle = handles.parent_handle.0;

        let (session_responses, num_sessions) = self.parse_and_validate_sessions(&mut request)?;

        let cmd = match request.try_unmarshal::<Import>() {
            Ok(cmd) => cmd,
            Err(e) => {
                let mut slice = request.remaining_slice();
                if let Ok(_enc_key) = tpm2::Tpm2bData::unmarshal(&mut slice)
                    && let Ok(_obj_pub) = tpm2::Tpm2bPublic::unmarshal(&mut slice)
                    && let Ok(_dup) = tpm2::Tpm2bPrivate::unmarshal(&mut slice)
                    && let Ok(_seed) = tpm2::Tpm2bEncryptedSecret::unmarshal(&mut slice)
                    && slice.len() >= 2
                {
                    let alg = u16::from_be_bytes([slice[0], slice[1]]);
                    if alg > 0x0080 {
                        return Err(TpmRc::VALUE.with(Position::parameter(5)));
                    }
                }
                return Err(e);
            }
        };
        if request.remaining_bytes() != 0 {
            return Err(TpmRc::SIZE.to_rc());
        }

        let object_public_struct = cmd
            .object_public
            .to_struct()
            .map_err(|e| e.in_parameter(2).to_rc())?;

        // 1. Resolve parent object or hierarchy seed and parameters
        let mut parent_seed_val = [0u8; 64];
        let mut parent_qn_buf = [0u8; 66];
        let parent_info = self.resolve_parent_object_or_hierarchy(
            parent_handle,
            &mut parent_seed_val,
            &mut parent_qn_buf,
            false, // expect_type_error
        )?;

        let parent_obj = if parent_handle >> 24 == 0x80 {
            self.global_state
                .find_transient_object(parent_handle)
                .cloned()
                .ok_or(TpmRc::REFERENCE_H0)?
        } else if parent_handle >> 24 == 0x81 {
            self.context
                .load_persistent_object(self.global_state, parent_handle)
                .map_err(|_| TpmRc::REFERENCE_H0)?
        } else {
            return Err(TpmRc::HANDLE.with(Position::handle(1)));
        };

        let parent_symmetric_is_null = match &parent_obj.public.parms_and_id {
            OwnedPublicParmsAndId::Rsa(parms, _) => parms.symmetric.is_none(),
            OwnedPublicParmsAndId::Ecc(parms, _) => parms.symmetric.is_none(),
            _ => true,
        };

        // 2. Validate parameter sizes and attributes (encryptionKey Pos1, symmetricAlg Pos5, objectPublic Pos2, then inSymSeed Pos4)
        match cmd.symmetric_alg {
            None => {
                if cmd.encryption_key.get_size() > 0 {
                    return Err(TpmRc::SIZE.with(Position::parameter(1)));
                }
            }
            Some(sym_def) => {
                let bits = sym_def.key_bits();
                if bits != 128 && bits != 256 && bits != 192 {
                    return Err(TpmRc::SYMMETRIC.with(Position::parameter(5)));
                }
                if !matches!(
                    sym_def.mode(),
                    Some(
                        TpmiAlgSymMode::CFB
                            | TpmiAlgSymMode::CTR
                            | TpmiAlgSymMode::OFB
                            | TpmiAlgSymMode::CBC
                            | TpmiAlgSymMode::ECB
                    )
                ) {
                    return Err(TpmRc::MODE.with(Position::parameter(5)));
                }
                let inner_key_len = (bits / 8) as usize;
                if cmd.encryption_key.get_size() > 0
                    && cmd.encryption_key.get_size() as usize != inner_key_len
                {
                    return Err(TpmRc::SIZE.with(Position::parameter(1)));
                }
            }
        }

        if object_public_struct.auth_policy.get_size() != 0
            && let Some(name_alg) = object_public_struct.name_alg
        {
            let digest_size = name_alg.digest_size();
            if object_public_struct.auth_policy.get_size() as usize != digest_size {
                return Err(TpmRc::SIZE.with(Position::parameter(2)));
            }
        }

        // Check unique/parameter sizes of objectPublic before checking attributes
        match &object_public_struct.parms_and_id {
            PublicParmsAndId::Rsa(rsa_parms, rsa_unique) => {
                let key_size_bytes = (rsa_parms.key_bits.0 / 8) as usize;
                if rsa_unique.get_size() > 0 && rsa_unique.get_size() as usize != key_size_bytes {
                    return Err(TpmRc::SIZE.with(Position::parameter(2)));
                }
            }
            PublicParmsAndId::Ecc(ecc_parms, point) => {
                let param_size = match ecc_parms.curve_id {
                    tpm2::TpmEccCurve::NistP192 => 24,
                    tpm2::TpmEccCurve::NistP224 => 28,
                    tpm2::TpmEccCurve::NistP256 | tpm2::TpmEccCurve::BNP256 => 32,
                    tpm2::TpmEccCurve::NistP384 => 48,
                    tpm2::TpmEccCurve::NistP521 => 66,
                    _ => 32,
                };
                if (point.x.get_size() > 0 && point.x.get_size() as usize != param_size)
                    || (point.y.get_size() > 0 && point.y.get_size() as usize != param_size)
                {
                    return Err(TpmRc::SIZE.with(Position::parameter(2)));
                }
            }
            _ => {}
        }

        if cmd.in_sym_seed.get_size() > 0 {
            if parent_symmetric_is_null {
                return Err(TpmRc::SIZE.with(Position::parameter(4)));
            }
            match &parent_obj.public.parms_and_id {
                OwnedPublicParmsAndId::Rsa(parms, _) => {
                    let expected_size = (parms.key_bits.0 / 8) as usize;
                    if cmd.in_sym_seed.get_size() as usize != expected_size {
                        return Err(TpmRc::SIZE.with(Position::parameter(4)));
                    }
                }
                OwnedPublicParmsAndId::Ecc(parms, _) => {
                    let mut slice = cmd.in_sym_seed.get_buffer();
                    let eph_point = tpm2::TpmsEccPoint::unmarshal(&mut slice)
                        .map_err(|_| TpmRc::ECC_POINT.with(Position::parameter(4)))?;
                    if !slice.is_empty() {
                        return Err(TpmRc::SIZE.with(Position::parameter(4)));
                    }
                    let param_size = match parms.curve_id {
                        tpm2::TpmEccCurve::NistP192 => 24,
                        tpm2::TpmEccCurve::NistP224 => 28,
                        tpm2::TpmEccCurve::NistP256 | tpm2::TpmEccCurve::BNP256 => 32,
                        tpm2::TpmEccCurve::NistP384 => 48,
                        tpm2::TpmEccCurve::NistP521 => 66,
                        _ => return Err(TpmRc::ECC_POINT.with(Position::parameter(4))),
                    };
                    if eph_point.x.get_size() as usize != param_size
                        || eph_point.y.get_size() as usize != param_size
                    {
                        return Err(TpmRc::ECC_POINT.with(Position::parameter(4)));
                    }
                }
                _ => {
                    return Err(TpmRc::SIZE.with(Position::parameter(4)));
                }
            }
        }

        // 3. Validate semantic attributes on objectPublic (Pos2) and symmetricAlg (Pos1) after size checks
        if cmd.symmetric_alg.is_none()
            && object_public_struct
                .object_attributes
                .contains(TpmaObject::ENCRYPTED_DUPLICATION)
        {
            return Err(TpmRc::ATTRIBUTES.with(Position::parameter(1)));
        }

        if object_public_struct
            .object_attributes
            .intersects(TpmaObject::FIXED_TPM | TpmaObject::FIXED_PARENT)
        {
            return Err(TpmRc::ATTRIBUTES.with(Position::parameter(2)));
        }

        self.validate_public_parameters(&object_public_struct, true)?;

        // 5. Compute object name
        let mut pub_buf = [0u8; tpm2::TpmtPublic::MAX_SIZE];
        let pub_len = object_public_struct.marshal(&mut pub_buf);
        let object_name = self.compute_name(object_public_struct.name_alg, &pub_buf[..pub_len])?;

        // 6. Recover inner blob from duplicate (removing outer wrapper if present)
        let mut inner_blob = [0u8; 2048];
        let inner_blob_len;

        let duplicate_bytes = cmd.duplicate.get_buffer();
        let mut seed = [0u8; 64];
        let mut seed_len = 0;

        if cmd.in_sym_seed.get_size() > 0 {
            if parent_symmetric_is_null {
                return Err(TpmRc::SIZE.with(Position::parameter(1)));
            }
            // Decrypt seed using parent private key
            seed_len = match &parent_obj.public.parms_and_id {
                OwnedPublicParmsAndId::Rsa(_, _) => self
                    .crypto()
                    .decrypt(
                        Alg::OAEP,
                        Alg::from(parent_obj.public.name_alg.ok_or(TpmRc::HASH.to_rc())?),
                        &parent_obj.private[..parent_obj.private_len],
                        cmd.in_sym_seed.get_buffer(),
                        &mut seed,
                        b"DUPLICATE\0",
                    )
                    .map_err(|_| TpmRc::FAILURE)?,
                OwnedPublicParmsAndId::Ecc(parms, unique) => {
                    // 1. Unmarshal the ephemeral public key from in_sym_seed
                    let mut slice = cmd.in_sym_seed.get_buffer();
                    let eph_point = tpm2::TpmsEccPoint::unmarshal(&mut slice)
                        .map_err(|_| TpmRc::ECC_POINT.with(Position::parameter(4)))?;

                    let curve = parms.curve_id;
                    let param_size = match curve {
                        tpm2::TpmEccCurve::NistP192 => 24,
                        tpm2::TpmEccCurve::NistP224 => 28,
                        tpm2::TpmEccCurve::NistP256 | tpm2::TpmEccCurve::BNP256 => 32,
                        tpm2::TpmEccCurve::NistP384 => 48,
                        tpm2::TpmEccCurve::NistP521 => 66,
                        _ => return Err(TpmRc::ECC_POINT.with(Position::parameter(4))),
                    };

                    let mut eph_pub_point = [0u8; 256];
                    let ex_buf = eph_point.x.get_buffer();
                    let ey_buf = eph_point.y.get_buffer();
                    if ex_buf.len() > param_size || ey_buf.len() > param_size {
                        return Err(TpmRc::ECC_POINT.with(Position::parameter(4)));
                    }
                    eph_pub_point[param_size - ex_buf.len()..param_size].copy_from_slice(ex_buf);
                    eph_pub_point[param_size * 2 - ey_buf.len()..param_size * 2]
                        .copy_from_slice(ey_buf);

                    if self
                        .crypto()
                        .validate_point(curve, &eph_pub_point[..param_size * 2])
                        .is_err()
                    {
                        return Err(TpmRc::ECC_POINT.with(Position::parameter(4)));
                    }

                    // 2. ECDH point multiply (Parent private scalar key * Ephemeral public point)
                    let mut ecdh_point = [0u8; 256];
                    self.crypto()
                        .point_multiply(
                            curve,
                            &parent_obj.private[..parent_obj.private_len],
                            &eph_pub_point[..param_size * 2],
                            &mut ecdh_point,
                        )
                        .map_err(|_| TpmRc::ECC_POINT.with(Position::parameter(4)))?;

                    // 3. Reconstruct parent's public point
                    let mut parent_pub_point = [0u8; 256];
                    let px_buf = unique.x.get_buffer();
                    let py_buf = unique.y.get_buffer();
                    if px_buf.len() > param_size || py_buf.len() > param_size {
                        return Err(TpmRc::VALUE.to_rc());
                    }
                    parent_pub_point[param_size - px_buf.len()..param_size].copy_from_slice(px_buf);
                    parent_pub_point[param_size * 2 - py_buf.len()..param_size * 2]
                        .copy_from_slice(py_buf);

                    // 4. KDFe to recover seed
                    let parent_name_alg = parent_obj.public.name_alg.ok_or(TpmRc::HASH.to_rc())?;
                    let digest_size = parent_name_alg.digest_size();
                    let total_bits = (digest_size * 8) as u32;

                    tpm2::crypto::kdf::kdfe(
                        self.crypto(),
                        parent_name_alg,
                        &ecdh_point[..param_size],
                        b"DUPLICATE",
                        &eph_pub_point[..param_size],
                        &parent_pub_point[..param_size],
                        total_bits,
                        &mut seed,
                    )
                    .map_err(|_| TpmRc::FAILURE)?;
                    digest_size
                }
                _ => return Err(TpmRc::TYPE.with(Position::handle(1))),
            };

            if duplicate_bytes.len() < 2 {
                return Err(TpmRc::SIZE.to_rc());
            }
            let mac_len = u16::from_be_bytes([duplicate_bytes[0], duplicate_bytes[1]]) as usize;
            if duplicate_bytes.len() < 2 + mac_len {
                return Err(TpmRc::SIZE.to_rc());
            }
            let mac_bytes = &duplicate_bytes[2..2 + mac_len];
            let encrypted_blob = &duplicate_bytes[2 + mac_len..];

            // Verify outer integrity HMAC and derive outer symmetric key/IV dynamically
            let mut sym_key_bits = match &parent_obj.public.parms_and_id {
                OwnedPublicParmsAndId::Rsa(parms, _) => {
                    parms.symmetric.map(|s| s.key_bits() as u32).unwrap_or(128)
                }
                OwnedPublicParmsAndId::Ecc(parms, _) => {
                    parms.symmetric.map(|s| s.key_bits() as u32).unwrap_or(128)
                }
                _ => 128,
            };
            if sym_key_bits == 0 {
                sym_key_bits = 128;
            }
            let outer_key_len = (sym_key_bits / 8) as usize;

            let mut sym_key_iv = [0u8; 48];
            let mut integrity_key = [0u8; 64];
            let mut computed_mac_bytes = [0u8; 64];

            let obj_name_alg = object_public_struct.name_alg.ok_or(TpmRc::HASH.to_rc())?;
            let obj_digest_size = obj_name_alg.digest_size();
            let obj_bits = (obj_digest_size * 8) as u32;
            kdfa(
                self.crypto(),
                obj_name_alg,
                &seed[..seed_len],
                b"INTEGRITY",
                &[],
                &[],
                obj_bits,
                &mut integrity_key,
            )
            .map_err(|_| TpmRc::FAILURE)?;
            kdfa(
                self.crypto(),
                obj_name_alg,
                &seed[..seed_len],
                b"STORAGE",
                object_name.get_buffer(),
                &[],
                sym_key_bits,
                &mut sym_key_iv,
            )
            .map_err(|_| TpmRc::FAILURE)?;

            let mut hmac_ctx = tpm2::crypto::HmacCtx::new(
                self.crypto(),
                obj_name_alg,
                &integrity_key[..obj_digest_size],
            )
            .map_err(|_| TpmRc::FAILURE)?;
            hmac_ctx
                .update(encrypted_blob)
                .map_err(|_| TpmRc::FAILURE)?;
            hmac_ctx
                .update(object_name.get_buffer())
                .map_err(|_| TpmRc::FAILURE)?;
            let hmac_res = hmac_ctx
                .finalize(&mut computed_mac_bytes)
                .map_err(|_| TpmRc::FAILURE)?;
            let computed_mac_len = hmac_res.digest().len();

            if computed_mac_bytes[..computed_mac_len] != *mac_bytes {
                return Err(TpmRc::INTEGRITY.to_rc());
            }

            let mut outer_key = [0u8; 32];
            outer_key[..outer_key_len].copy_from_slice(&sym_key_iv[..outer_key_len]);
            let mut outer_iv = [0u8; 16]; // IV is all zeros for CFB mode duplication

            if encrypted_blob.len() > inner_blob.len() {
                return Err(TpmRc::SIZE.to_rc());
            }
            inner_blob_len = encrypted_blob.len();
            inner_blob[..inner_blob_len].copy_from_slice(encrypted_blob);

            let sym_alg = tpm2::TpmtSymDefObject::aes_cfb((outer_key_len * 8) as u16)
                .map_err(|_| TpmRc::FAILURE)?;
            tpm2::crypto::decrypt(
                self.crypto(),
                sym_alg,
                &outer_key[..outer_key_len],
                &mut outer_iv,
                &mut inner_blob[..inner_blob_len],
            )
            .map_err(|_| TpmRc::FAILURE)?;
        } else {
            // No outer wrapper
            if object_public_struct
                .object_attributes
                .contains(TpmaObject::ENCRYPTED_DUPLICATION)
            {
                return Err(TpmRc::ATTRIBUTES.with(Position::parameter(4)));
            }
            if duplicate_bytes.len() > inner_blob.len() {
                return Err(TpmRc::SIZE.to_rc());
            }
            inner_blob_len = duplicate_bytes.len();
            inner_blob[..inner_blob_len].copy_from_slice(duplicate_bytes);
        }

        let mut decrypted_inner = [0u8; 2048];
        let sensitive_struct = if let Some(sym_def) = cmd.symmetric_alg {
            let mut inner_key = [0u8; 32];
            let inner_key_len = sym_def.key_bits() as usize / 8;

            if cmd.encryption_key.get_size() > 0 {
                if cmd.encryption_key.get_size() as usize != inner_key_len {
                    return Err(TpmRc::SIZE.with(Position::parameter(1)));
                }
                inner_key[..inner_key_len].copy_from_slice(cmd.encryption_key.get_buffer());
            } else {
                // Derive inner symmetric wrapper key from the decrypted seed
                if cmd.in_sym_seed.get_size() == 0 {
                    return Err(TpmRc::SIZE.with(Position::parameter(4)));
                }
                let total_bits = (inner_key_len * 8) as u32;

                let name_alg = object_public_struct.name_alg.ok_or(TpmRc::HASH.to_rc())?;
                kdfa(
                    self.crypto(),
                    name_alg,
                    &seed[..seed_len],
                    b"STORAGE",
                    object_name.get_buffer(),
                    &[],
                    total_bits,
                    &mut inner_key,
                )
                .map_err(|_| TpmRc::FAILURE)?;
            }

            decrypted_inner[..inner_blob_len].copy_from_slice(&inner_blob[..inner_blob_len]);

            let mut iv = [0u8; 16];
            let sym_alg = tpm2::TpmtSymDefObject::aes_cfb((inner_key_len * 8) as u16)
                .map_err(|_| TpmRc::FAILURE)?;
            tpm2::crypto::decrypt(
                self.crypto(),
                sym_alg,
                &inner_key[..inner_key_len],
                &mut iv,
                &mut decrypted_inner[..inner_blob_len],
            )
            .map_err(|_| TpmRc::FAILURE)?;

            if inner_blob_len < 2 {
                return Err(TpmRc::SIZE.to_rc());
            }
            let inner_integrity_len =
                u16::from_be_bytes([decrypted_inner[0], decrypted_inner[1]]) as usize;
            let sensitive_offset = 2 + inner_integrity_len;
            if sensitive_offset + 2 > inner_blob_len {
                return Err(TpmRc::SIZE.to_rc());
            }
            let sensitive_size = u16::from_be_bytes([
                decrypted_inner[sensitive_offset],
                decrypted_inner[sensitive_offset + 1],
            ]) as usize;
            if sensitive_offset + 2 + sensitive_size > inner_blob_len {
                return Err(TpmRc::SIZE.to_rc());
            }

            if inner_integrity_len > 0 {
                let mut computed_inner_mac = [0u8; 64];
                let integrity_data_slice = &decrypted_inner
                    [2 + inner_integrity_len..2 + inner_integrity_len + 2 + sensitive_size];

                let name_alg = object_public_struct.name_alg.ok_or(TpmRc::HASH.to_rc())?;
                let (hash_bytes, computed_inner_mac_len) =
                    self.compute_hash(name_alg, &[integrity_data_slice, object_name.get_buffer()])?;
                computed_inner_mac[..computed_inner_mac_len]
                    .copy_from_slice(&hash_bytes[..computed_inner_mac_len]);

                if computed_inner_mac_len != inner_integrity_len
                    || computed_inner_mac[..computed_inner_mac_len]
                        != decrypted_inner[2..2 + inner_integrity_len]
                {
                    return Err(TpmRc::INTEGRITY.to_rc());
                }
            }

            let sensitive_bytes =
                &decrypted_inner[sensitive_offset + 2..sensitive_offset + 2 + sensitive_size];
            let mut slice = sensitive_bytes;
            let sensitive_struct =
                TpmtSensitive::unmarshal(&mut slice).map_err(|_| TpmRc::VALUE.to_rc())?;
            if !slice.is_empty() {
                return Err(TpmRc::SIZE.to_rc());
            }
            sensitive_struct
        } else {
            // No inner wrapper, sensitive area was marshalled inside TPM2B_PRIVATE (with a 2-byte size prefix)
            if inner_blob_len < 2 {
                return Err(TpmRc::SIZE.to_rc());
            }
            let sensitive_size = u16::from_be_bytes([inner_blob[0], inner_blob[1]]) as usize;
            if 2 + sensitive_size > inner_blob_len {
                return Err(TpmRc::SIZE.to_rc());
            }
            let mut slice = &inner_blob[2..2 + sensitive_size];
            let sensitive_struct =
                TpmtSensitive::unmarshal(&mut slice).map_err(|_| TpmRc::VALUE.to_rc())?;
            if !slice.is_empty() {
                return Err(TpmRc::SIZE.to_rc());
            }
            sensitive_struct
        };

        if parent_info.attributes.contains(TpmaObject::FIXED_TPM)
            || parent_handle == 0x40000001
            || parent_handle == 0x4000000C
            || parent_handle == 0x4000000B
        {
            self.validate_object_attributes(
                &object_public_struct,
                parent_handle,
                parent_info.hierarchy_val,
                Some(parent_info.attributes),
                true,  // is_import
                false, // allow_null_name_alg
                Position::parameter(2),
            )?;
            self.validate_public_parameters(&object_public_struct, true)?;
        }

        // 6. Public-Private consistency check and import validation
        // Per TCG Part 3 Section 13.3.3: if parent has fixedTPM set, binding/sensitive validation must be checked on import.
        // If parent has fixedTPM clear, binding and secret formatting validation need only be checked when the object is loaded.
        let mut actual_private_key = [0u8; 1536];
        let actual_private_key_len = if parent_obj
            .public
            .object_attributes
            .contains(TpmaObject::FIXED_TPM)
        {
            self.validate_and_import_sensitive(
                &object_public_struct,
                &sensitive_struct,
                &mut actual_private_key,
                Position::parameter(3),
                Position::parameter(2),
                true,
            )?
        } else {
            match self.validate_and_import_sensitive(
                &object_public_struct,
                &sensitive_struct,
                &mut actual_private_key,
                Position::parameter(3),
                Position::parameter(2),
                true,
            ) {
                Ok(len) => len,
                Err(_) => {
                    // Defer binding/key errors to load; copy raw unmarshaled sensitive data
                    match &sensitive_struct.sensitive {
                        TpmuSensitiveComposite::Rsa(rsa_priv) => {
                            let buf = rsa_priv.get_buffer();
                            actual_private_key[..buf.len()].copy_from_slice(buf);
                            buf.len()
                        }
                        TpmuSensitiveComposite::Ecc(ecc_priv) => {
                            let buf = ecc_priv.get_buffer();
                            actual_private_key[..buf.len()].copy_from_slice(buf);
                            buf.len()
                        }
                        TpmuSensitiveComposite::Sym(sym_key) => {
                            let buf = sym_key.get_buffer();
                            actual_private_key[..buf.len()].copy_from_slice(buf);
                            buf.len()
                        }
                        TpmuSensitiveComposite::KeyedHash(bits_data) => {
                            let buf = bits_data.get_buffer();
                            actual_private_key[..buf.len()].copy_from_slice(buf);
                            buf.len()
                        }
                        TpmuSensitiveComposite::Mldsa(mldsa_priv)
                        | TpmuSensitiveComposite::HashMldsa(mldsa_priv) => {
                            let buf = mldsa_priv.get_buffer();
                            actual_private_key[..buf.len()].copy_from_slice(buf);
                            buf.len()
                        }
                        TpmuSensitiveComposite::Mlkem(mlkem_priv) => {
                            let buf = mlkem_priv.get_buffer();
                            actual_private_key[..buf.len()].copy_from_slice(buf);
                            buf.len()
                        }
                    }
                }
            }
        };

        // 7. Re-encrypt under the new parent key
        let sensitive_create = TpmsSensitiveCreate {
            user_auth: sensitive_struct.auth_value,
            data: tpm2::Tpm2bSensitiveData::default(),
        };
        let mut private_buf = [0u8; 2048];
        let out_private = self.create_and_encrypt_private_area(
            &object_public_struct,
            &sensitive_create,
            &actual_private_key[..actual_private_key_len],
            sensitive_struct.seed_value.get_buffer(),
            &parent_seed_val[..parent_info.seed_len],
            &object_name,
            false,
            false,
            parent_info.name_alg,
            parent_info.sym_bits,
            &mut private_buf,
        )?;

        let rsp = responses::Import { out_private };

        // Write response
        let response = request.into_response();
        self.write_response_all(response, &(), &rsp, &session_responses[..num_sessions])?;
        Ok(())
    }
}
