use crate::handler::CommandHandler;
use crate::req_resp::RequestThenResponse;
#[allow(unused_imports)]
use tpm2::TpmCc;
use tpm2::Unmarshal;
use tpm2::commands::{PolicyAuthorize, PolicyAuthorizeHandles};
use tpm2::errors::{Position, TpmRc};

use crate::storage::NvStorage;
use crate::timer::TpmTimer;
use tpm2::crypto::{CryptoProvider, Rng};
use tpm2::{Handle, TpmSe, TpmiAlgHash};

impl<'a, 'b, C: CryptoProvider, S: NvStorage, T: TpmTimer, R: Rng + Sync>
    CommandHandler<'a, 'b, C, S, T, R>
{
    /// Handles the [TpmCc::PolicyAuthorize] (`0x16A`) command.
    ///
    /// # Description
    /// This command allows a policy to be authorized dynamically by an authority.
    /// It resets the session's policy digest and extends it with the authority's key name,
    /// authorizing the approved policy signed by that authority.
    ///
    /// # Spec Citation
    /// TCG TPM 2.0 Library Specification, Part 3: Commands, Section 23.16 (TPM2_PolicyAuthorize).
    ///
    /// # Relationships
    /// - Validates a ticket (`checkTicket`) generated by verifying a signature over the approved policy,
    ///   typically obtained from [TpmCc::VerifySignature](crypt_ops.rs).
    /// - The `approved_policy` parameter must match the current value of the policy session digest.
    pub fn policy_authorize(
        &mut self,
        request_response: RequestThenResponse<'_, '_>,
    ) -> Result<(), TpmRc> {
        let mut request = request_response;

        let handles = request.try_unmarshal::<PolicyAuthorizeHandles>()?;
        let policy_session = handles.policy_session.0;

        let (session_responses, num_sessions) = self.parse_and_validate_sessions(&mut request)?;

        let cmd = request.try_unmarshal::<PolicyAuthorize>()?;
        if request.remaining_bytes() != 0 {
            return Err(TpmRc::SIZE.to_rc());
        }

        // Validate session expiration
        self.validate_policy_session(policy_session, Position::handle(1))?;

        // 1. Retrieve policy session details

        let (auth_hash, policy_digest, policy_digest_len, session_type) = {
            let session_state = self
                .global_state
                .session(policy_session)
                .ok_or(TpmRc::HANDLE.with(Position::handle(1)))?;
            if session_state.session_type != TpmSe::Policy
                && session_state.session_type != TpmSe::Trial
            {
                return Err(TpmRc::HANDLE.with(Position::handle(1)));
            }
            (
                session_state.auth_hash,
                session_state.policy_digest,
                session_state.policy_digest_len,
                session_state.session_type,
            )
        };

        let mut key_sign_src = cmd.key_sign.get_buffer();
        if key_sign_src.len() < 2 {
            return Err(TpmRc::SIZE.with(Position::parameter(3)));
        }

        let hash_alg = TpmiAlgHash::unmarshal(&mut key_sign_src)
            .map_err(|_| TpmRc::HASH.with(Position::parameter(3)))?;

        if key_sign_src.len() != hash_alg.digest_size() {
            return Err(TpmRc::SIZE.with(Position::parameter(3)));
        }

        if session_type == TpmSe::Policy {
            // Verify approvedPolicy matches current policy digest
            if cmd.approved_policy.get_buffer() != &policy_digest[..policy_digest_len] {
                return Err(TpmRc::VALUE.with(Position::parameter(1)));
            }

            let ticket_hierarchy = cmd.check_ticket.hierarchy().0;
            if ticket_hierarchy != Handle::RH_OWNER.0
                && ticket_hierarchy != Handle::RH_ENDORSEMENT.0
                && ticket_hierarchy != Handle::RH_PLATFORM.0
            {
                return Err(TpmRc::VALUE.with(Position::parameter(4)));
            }
            if cmd.check_ticket.digest().get_buffer().is_empty() {
                return Err(TpmRc::VALUE.with(Position::parameter(4)));
            }

            let expected_hmac = match cmd.check_ticket {
                tpm2::TpmtTkVerified::Verified(..) => {
                    // re-compute aHash = hash(approvedPolicy || policyRef)
                    let (auth_hash_bytes, auth_hash_len) = self.compute_hash(
                        hash_alg,
                        &[
                            cmd.approved_policy.get_buffer(),
                            cmd.policy_ref.get_buffer(),
                        ],
                    )?;
                    self.compute_verified_ticket_with_meta(
                        ticket_hierarchy,
                        0x8022,
                        &auth_hash_bytes[..auth_hash_len],
                        cmd.key_sign.get_buffer(),
                        &[],
                    )?
                }
                tpm2::TpmtTkVerified::MessageVerified(..) => {
                    let mut msg = [0u8; 128];
                    let ap = cmd.approved_policy.get_buffer();
                    let pr = cmd.policy_ref.get_buffer();
                    if ap.len() + pr.len() > msg.len() {
                        return Err(TpmRc::SIZE.to_rc());
                    }
                    msg[..ap.len()].copy_from_slice(ap);
                    msg[ap.len()..ap.len() + pr.len()].copy_from_slice(pr);
                    self.compute_verified_ticket_with_meta(
                        ticket_hierarchy,
                        0x8026,
                        &msg[..ap.len() + pr.len()],
                        cmd.key_sign.get_buffer(),
                        &[],
                    )?
                }
                tpm2::TpmtTkVerified::DigestVerified(_, digest_alg, _) => {
                    let (auth_hash_bytes, auth_hash_len) = self.compute_hash(
                        digest_alg,
                        &[
                            cmd.approved_policy.get_buffer(),
                            cmd.policy_ref.get_buffer(),
                        ],
                    )?;
                    let meta_bytes = tpm2::Alg::from(digest_alg).id().to_be_bytes();
                    self.compute_verified_ticket_with_meta(
                        ticket_hierarchy,
                        0x8027,
                        &auth_hash_bytes[..auth_hash_len],
                        cmd.key_sign.get_buffer(),
                        &meta_bytes,
                    )?
                }
            };

            if cmd.check_ticket.digest().get_buffer() != expected_hmac.as_slice() {
                return Err(TpmRc::VALUE.with(Position::parameter(4)));
            }
        }

        // 2. Clear policyDigest
        {
            let session_state = self
                .global_state
                .session_mut(policy_session)
                .ok_or(TpmRc::HANDLE.to_rc())?;
            session_state.policy_digest[..session_state.policy_digest_len].fill(0);
        }

        // 3. Compute new policy digest
        // digest1 = hash(policyDigest_old || TPM_CC_PolicyAuthorize || keySign)
        let zero_digest = [0u8; 64];
        let (digest1, digest1_len) = self.compute_hash(
            auth_hash,
            &[
                &zero_digest[..policy_digest_len],
                &0x0000016Au32.to_be_bytes(), // TPM_CC_PolicyAuthorize
                cmd.key_sign.get_buffer(),
            ],
        )?;

        // new_digest = hash(digest1 || policyRef)
        let (new_digest, new_digest_len) = self.compute_hash(
            auth_hash,
            &[&digest1[..digest1_len], cmd.policy_ref.get_buffer()],
        )?;

        // Update session state in global_state
        {
            let session_state = self
                .global_state
                .session_mut(policy_session)
                .ok_or(TpmRc::HANDLE.to_rc())?;
            session_state.policy_digest[..new_digest_len]
                .copy_from_slice(&new_digest[..new_digest_len]);
            session_state.policy_digest_len = new_digest_len;
        }

        // 4. Write empty response
        let response = request.into_response();
        self.write_response_none(response, &session_responses[..num_sessions])?;

        Ok(())
    }
}
