[package]
name = "tpm2-impl"
# Inherit from Workspace Settings
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hex-literal = { workspace = true }
tpm2 = { workspace = true }

[dev-dependencies]
tpm2-crypto-rust = { workspace = true }
tpm2-crypto-crux = { workspace = true }
tpm2-crypto-bssl = { workspace = true }

[features]
default = ["dev_crypto_bssl"]
dev_crypto_rust = []
dev_crypto_crux = []
dev_crypto_bssl = []



